In [3]:
import torch

In [4]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
import numpy as np
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [8]:
tensor = torch.rand(3, 4)
print(tensor.shape, '/', tensor.dtype, '/', tensor.device)

torch.Size([3, 4]) / torch.float32 / cpu


In [9]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [6]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [7]:
print(len(training_data))

60000


In [8]:
first_image = training_data[0][0]
print(first_image.shape)

torch.Size([1, 28, 28])


In [10]:
test = test_data[0][0]
print(test.shape)

torch.Size([1, 28, 28])


In [11]:
print(len(test_data))

10000
